title: "Tanya Tree — Learning in Public"
description: "Notes, experiments, and portfolio — Python/Django, patterns, and aha moments."
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: "Tanya Tree"
markdown: kramdown
highlighter: rouge
future: true
show_excerpts: true
