title: "Tanya Tree — Learning in Public"
description: "Notes, experiments, and portfolio — Python/Django, patterns, and aha moments."
remote_theme: "jekyll/minima@1e8a445"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: "Tanya Tree"

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/tanyatree" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/tanya-tr%C3%ADfero-1880945a/" }
markdown: kramdown
highlighter: rouge
future: true
show_excerpts: true
