title: "Tanya Tree — Learning in Public"
description: "Notes, experiments, and portfolio — Python/Django, patterns, and aha moments."
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Tanya Tree"
  github: "tanyatree"

minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/tanyatree" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/tanya-tr%C3%ADfero-1880945a/" }
markdown: kramdown
highlighter: rouge
