title: "🌲 Tanya Tree — Learning in Public"
description: "Notes, experiments, and portfolio — Python/Django, patterns, and aha moments."
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: "Tanya Tree"

minima:
  skin: dark
  show_excerpts: true
  social_links:
    - title: Tanya Tree repository at GitHub
      icon: github
      url: "https://github.com/tanyatree"
    - title: Tanya Tree LinkedIn profile
      icon: linkedin
      url: "https://www.linkedin.com/in/tanya-tr%C3%ADfero-1880945a/"
  nav_pages:
    - index.md        # "Welcome"
    - cheatsheets.md  # "Cheatsheets"
    - projects.md     # "Projects"
    - about.md        # "About"
markdown: kramdown
highlighter: rouge
future: true

collections:
  cheatsheets:
    output: true
    permalink: /cheatsheets/:name/
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "cheatsheets"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
