title: "Tanya Tree — Learning in Public"
description: "Notes, experiments, and portfolio — Python/Django, patterns, and aha moments."
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: "Tanya Tree"

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/tanyatree" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/tanya-tr%C3%ADfero-1880945a/" }
markdown: kramdown
highlighter: rouge
future: true
show_excerpts: true

collections:
  cheatsheets:
    output: true
    permalink: /cheatsheets/:name/

defaults:
  - scope:
      path: ""
      type: "cheatsheets"
    values:
      layout: "page"
